apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultscope.fullname" . }}-secret
  labels:
    {{- include "vaultscope.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.env.JWT_SECRET | b64enc | quote }}
  session-secret: {{ .Values.env.SESSION_SECRET | b64enc | quote }}
  {{- if .Values.influxdb.enabled }}
  influxdb-token: {{ .Values.influxdb.token | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  ldap-password: {{ .Values.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.enabled }}
  {{- if .Values.oauth.providers.google.enabled }}
  google-client-secret: {{ .Values.oauth.providers.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.providers.github.enabled }}
  github-client-secret: {{ .Values.oauth.providers.github.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.providers.azure.enabled }}
  azure-client-secret: {{ .Values.oauth.providers.azure.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}