apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultscope.fullname" . }}
  labels:
    {{- include "vaultscope.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.ha.enabled }}
  sessionAffinity: {{ .Values.ha.sessionAffinity }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vaultscope.selectorLabels" . | nindent 4 }}