apiVersion: v2
name: vaultscope-statistics
description: Enterprise System Monitoring and Management Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - statistics
  - alerting
  - metrics
  - dashboard
home: https://github.com/vaultscope/statistics
sources:
  - https://github.com/vaultscope/statistics
maintainers:
  - name: VaultScope - CPTCR
    email: cptcr@proton.me
icon: https://cptcr.dev/icon.png
dependencies:
  - name: influxdb2
    version: "2.1.1"
    repository: "https://helm.influxdata.com/"
    condition: influxdb.enabled
  - name: redis
    version: "18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "13.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled